# Generated by Django 4.1.7 on 2023-03-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_carusel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryL0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryL1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l0_l1', to='main.categoryl0')),
            ],
        ),
    ]
