# Generated by Django 4.1.7 on 2023-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categoryl0_categoryl1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50, verbose_name='Product head')),
                ('img', models.ImageField(upload_to='product', verbose_name='Product head')),
                ('price', models.PositiveBigIntegerField(verbose_name='Product price')),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Not Available', 'Not Available')], max_length=30, verbose_name='availability')),
            ],
        ),
    ]
