# Generated by Django 4.1.7 on 2023-03-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_condition_product_cotegory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product', verbose_name='Product image'),
        ),
    ]
